import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import { LoadingProvider } from './context/LoadingContext';
import Loading from './components/Loading';
import { ApiProvider } from "./context/ApiContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Suspense>
          <ApiProvider>
            <LoadingProvider>
              <Loading />
              {children}
            </LoadingProvider>
          </ApiProvider>
        </Suspense>
      </body>
    </html>
  );
}
